### ISSUE TITLE
Business requirements - API send & receive forms to the server 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#103]
Technical issue
Nie wysyła formularzy na serwer 

**Tasks**

- [x] implement endpoitns 

- [x] API solutions

**Comment by maggienow** [comment]
Ania,Adam - potrzebujecie tutaj wsparcia Michała?

**Comment by adam-sas-on** [comment]
I think not or not yet.
Development with him would be faster naturally
bu it is not necessary.

**Comment by annapakula** [comment]
@adam-sas-on to chyba można zamknąć?

**Comment by adam-sas-on** [comment]
It seems yes :-)
Let's close it then.
