### ISSUE TITLE
User Log In - Django and Looper

### ISSUE THREAD

**Issue by roktiw** [binawork/OnlineOnboarding#11]
**User story** 
As a user I would like to have a registration form where I can put my data as well as having a point to log in.

**Definition of ready** 

**Definition of Done** 

- [x] Style Registration Form form Django with Looper @adam-sas-on
- [x] Verify that Django gets request from Registration Form styled with Looper @adam-sas-on

![image](https://user-images.githubusercontent.com/67949340/87351639-00d66300-c55a-11ea-89eb-5db8c59ce443.png)

**Comment by adam-sas-on** [comment]
It seems to be finished (some others also),
I'm wondering if it is time (good moment) for `pull-request`

**Comment by maggienow** [comment]
@roktiw @adam-sas-on   - could you put the definition of ready and definition of done to this issue? I have also doubts about sign in and log in - do we have it divided?
