### ISSUE TITLE
Business requirement - API to questions and answers in forms 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#117]
Technical issue 
-Edition of forms 

**Tasks**

- [x] Create API to questions and answers in forms 

- [x] Migration for front end

**Comment by maggienow** [comment]
@annapakula @MichalKandybowicz  - Ania, Michal czy tutaj to juz jest zrobione? jezeli tak, to zamknijcie prosze ten issue

**Comment by annapakula** [comment]
@maggienow Nie, to jest to co robiłam w zeszłym tygodniu. Udało mi się naprawić to, o czym dzisiaj mówiłam, ale znalazłam z kolei błąd przy przesyłaniu obrazków do bazy danych.
