### ISSUE TITLE
Technical issue  - Progress of pages for user / HR manager 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#119]
**Issue** 
There is no progress seen in the list of forms sent to employee  

**Tasks**

- [x] Backend check why it doesn't work

- [x] Frontend confirms when it works

**Comment by maggienow** [comment]
@adam-sas-on @MichalKandybowicz - rozumiem, że to jest nadal w trakcie robienia ? i to jest Adam to,co bedziesz robił w tym tygodniu?

**Comment by adam-sas-on** [comment]
Before finishing this issue of progress for user
I think we/I should do the functionality of user fulfilling forms (which I'm working on now).
When it will be done then there will be a chance to test all those features together. :-)

**Comment by maggienow** [comment]
Implement progress to be seen by HR manager on his/ her dashboard

**Comment by maggienow** [comment]
Progress must be seen also for user
