### ISSUE TITLE
Fixing Update admin.py file

### ISSUE THREAD

**Issue by topi-chan** [binawork/OnlineOnboarding#183]
Change CustomUserAdmin class and register it in admin.py; make custom user model more readable in Django Admin panel, and maybe customise other models view.

**Comment by maggienow** [comment]
Maciej- co dla Ciebie znaczy  ta labellka "good first issue" ? Bo nie wiem, do czego to podpinać.

**Comment by topi-chan** [comment]
Że to dobry temat dla początkującego w teamie (bo do tego nie trzeba resta).
Można dać jako „feature” (ale to jest „feature” wewnętrzne, nie dla usera, tylko dla admina)

Wysłane z iPhone'a
