### ISSUE TITLE
Analyze the landing page

### ISSUE THREAD

**Issue by adam-sas-on** [binawork/OnlineOnboarding#19]
Choose skins/images,
decide what to change and what to leave
as it was mentioned during stand-up meeting.
([Onboarding landing page branch](https://github.com/binawork/OnlineOnboarding/tree/landing_page)

**Comment by maggienow** [comment]
@roktiw  - please give feedback to @adam-sas-on if this meets your requirements

**Comment by maggienow** [comment]
Redirect to manage after the log in @adam-sas-on
