### ISSUE TITLE
Balsamiq

### ISSUE THREAD

**Issue by onlineonboarding** [binawork/OnlineOnboarding#34]
- [x] changes by @roktiw 
- [ ] review from @MichalKandybowicz 
- [ ] Create new Milestone on Github, and 1 ticket for each view on Balsamiq @maggienow 

https://balsamiq.cloud/sviuzng/p1y6lm3

**Comment by maggienow** [comment]
@MichalKandybowicz  please tell me how the milestone should be described. As we have some empty milestone.
