### ISSUE TITLE
Landing Page content

### ISSUE THREAD

**Issue by adam-sas-on** [binawork/OnlineOnboarding#42]
USER STORY 
As a user I want to have landing page in Polish and English version 

Definition of ready 
I have written down the content for  landing page in ENG & PL 
**Definition of done** 
 Content in Polish written and implemented to landing page 

Tasks:

- [x] @MichalKandybowicz will write down the content for landing page in Polish

- [x] @maggienow will translate into English the content for landing page in Polish

**Comment by maggienow** [comment]
@Michal-Roszyk - czy możesz proszę sprawdzić jakie obrazki by pasowały na nasza landing page?  i coś nam zaproponowac. Żeby ten landing page wyglądał.
