### ISSUE TITLE
Business requirements - Add Google analytics 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#52]
**User story** 
As a starup we want to know stars of our landing page and who is visiting (bits or real people) so we can track our landing performance. 

**Task:** 
[] Add Google Analytics to our gmail account
[] add tracking code to head 

**Definition of ready** 
Google analytics tracking landing page performance

**Comment by roktiw** [comment]
Credentials for our Google Analitics https://github.com/binawork/OnlineOnboarding#gmail---google-analitics

**Comment by adam-sas-on** [comment]
Server has G. Analytics already
