### ISSUE TITLE
Business requirements - extened HR register form 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#70]
**Tasks**
- [ ] add text box - Company name 

**DOR**
When user at the registration will be creating "Company profile" 

**DOD**
When Michal will check this.

**Comment by kMatejak** [comment]
[suggestion]
Maybe it would be worth if the company name was not entered manually by the user (HR) [when adding another user], but added directly from the company name, which is in the user account (HR).

**Comment by maggienow** [comment]
Panowie - czy to jest zrobione?

**Comment by kMatejak** [comment]
Done
