### ISSUE TITLE
Business requirements - USER Login 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#78]
There is an issue to log into system after setting up new account 

![image](https://user-images.githubusercontent.com/67949340/93327869-3f6af100-f81b-11ea-9e09-557616f2bb5c.png)

**Comment by MichalKandybowicz** [comment]
wpisany przez ciebie link prowadzi do nikąd (nie mamy takiej strony), więc wszystko działa jak powinno :)
