### ISSUE TITLE
Business requirements - Add markdown edition in questions

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#88]
**user story**
As HR manager I want to have an option to edit text in creating questions

**Tasks**

- [x] Add markdown pole in open answer section

**Comment by maggienow** [comment]
@MichalKandybowicz - czy możesz Adamowi odpowiedzieć, czy na pewno chcesz ,zeby była obłsuga formatowania w "open answer" section?

**Comment by MichalKandybowicz** [comment]
żadne formatowanie tekstu się nie pojawia w pytaniach czy odpowiedziach

**Comment by annapakula** [comment]
Added markdown edition in open, single and multiple choice questions.
